### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by igbanam** [zhishi-project/zhishi-backend#120]
Currently, the infrastructure this project is built on is dated. Some of the fundamental things to Rails development such as `rails c` and `rspec` don't seem to work. I believe this is tied to the fact that we are currently on Rails 2. 

My proposal here is that we upgrade the codebase to the latest rails version. Production can still remain Rails 2 until we have stabilized Rails 5 locally.

Doing this may be difficult because upgrading Rails is usually done behind benchmark testing. As it stands, RSpec does not run. I hope this does not lead to some sort of rewriting the application.

**Comment by igbanam** [comment]
Note the time this message is being post. Then check the time in the picture. That's how long the process has been waiting. 

<img width="715" alt="1__ruby" src="https://user-images.githubusercontent.com/390059/29250310-7f33bea6-8038-11e7-8366-1a744d45c930.png">

**Comment by andela-oakinniranye** [comment]
The app is currently on [Rails 4.2.5](https://github.com/zhishi-project/zhishi-backend/blob/master/Gemfile#L5), however, I agree we should upgrade to Rails 5, it was one of our plans, however, Rails5 was still unstable(or in beta, can't remember specifically), when we started building this.
The specific error you're seeing seem to be related to Spring and Rubygem [here](https://github.com/rubygems/rubygems/commit/a6b69e94232166dda441bbb69b64cf90562eebfd) and [here](https://github.com/rubygems/rubygems/issues/1551), but I don't believe it should disturb an upgrade. [echoing what you said]: I'd prefer we have an upgrade plan as well and I believe we have sufficient test coverage on this to prevent any regressions, we may want to run some performance testing before the final upgrade reaches prod too
